name: CI/CD
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#on:
#  workflow_run:
#    workflows: ["CI/CD"]
#    branches: [main]
#    types: 
#      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Prepare_Repository:
    name: Compile and deploy to production server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages  
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: mvn --batch-mode deploy 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
